### ISSUE TITLE
This project has no code license

### ISSUE THREAD

**Issue by Ana06** [openSUSE/obs-landing#103]
I am not sure if any of you realised or if this is done on propose, but this project has no license. That means that it has exclusive copyright and it is not open source. 😭 😭 

I would like that we change this, but for this we need the agreement of **all** the contributors to this project. I would go for a [MIT License](https://choosealicense.com/licenses/mit), but it someone has any concerns with it, we can go for a more restrictive license. In case that someone want to read about licenses, Github explain it in a really simple way: https://choosealicense.com

@hennevogel, @adrianschroeter, @bgeuken, @mdeniz, @smithfarm, @DavidKang, @sknorr, @evanrolfe, @ChrisBr, @fcrozat, @eduardoj, @marcus-h, @wengel, @lethliel, @mschnitzer, @shyukri and @bmwiedemann what do you think?

**Comment by eduardoj** [comment]
I agree with applying a MIT License.

**Comment by smithfarm** [comment]
I don't have any code in this project.

**Comment by sknorr** [comment]
I don't have any code in this project either. (I had changed two-ish lines of CSS but that was before the recent refresh of the homepage.)

**Comment by bmwiedemann** [comment]
MIT license will be fine. GPL-2.0 would work too.

**Comment by bgeuken** [comment]
Fine with me

**Comment by lethliel** [comment]
I don't have code here.

**Comment by mschnitzer** [comment]
I don't mind.

**Comment by Ana06** [comment]
@hennevogel, @adrianschroeter, @DavidKang, @evanrolfe, @ChrisBr, @fcrozat, @marcus-h, @wengel, @shyukri ^^

**Comment by fcrozat** [comment]
fine for me

**Comment by evanrolfe** [comment]
I'm fine with any decision on this.

**Comment by DavidKang** [comment]
@Ana06, fine for me 😄

**Comment by shyukri** [comment]
fine for me

**Comment by marcus-h** [comment]
On 2017-12-28 10:41:56 +0000, Ana María Martínez Gómez wrote:
> I would like that we change this, but for this we need the agreement of **all** the contributors to this projects. I would go for a [MIT License](https://choosealicense.com/licenses/mit),

I'm fine with MIT. Since I haven't done any substantial contributions
to this project, I'm probably also fine with any other license that the
main authors prefer.

**Comment by ChrisBr** [comment]
LGTM

**Comment by hennevogel** [comment]
fine by me

**Comment by Ana06** [comment]
@adrianschroeter, @wengel ^^
