### ISSUE TITLE
The content has no license

### ISSUE THREAD

**Issue by Ana06** [openSUSE/obs-landing#104]
As in this project we publish blog posts, which include content such as text or images, I would like to discuss using a content license for our blog posts.

We could allow to have difference licenses for every blog post, but it would be much better if we reach an agreement as we many times write the blog posts as a team and more than one person participate on writing them.

I would suggest using a [Creative Commons Attribution 4.0](https://choosealicense.com/licenses/cc-by-4.0).

This can be applied only to new posts, but it would be even better if we add it to old blog posts as well. We could only add the license to the old blog posts, whose author/s are fine with it.

@hennevogel, @adrianschroeter, @bgeuken, @mdeniz, @smithfarm, @DavidKang, @sknorr, @evanrolfe, @ChrisBr, @fcrozat, @eduardoj, @marcus-h, @wengel, @lethliel, @mschnitzer, @shyukri and @bmwiedemann what do you think?

**Comment by eduardoj** [comment]
I agree with applying a Creative Commons Attribution 4.0 license.

**Comment by bgeuken** [comment]
> eduardoj commented 5 days ago
> I agree with applying a Creative Commons Attribution 4.0 license.


Me too

**Comment by lethliel** [comment]
I agree too.

**Comment by mschnitzer** [comment]
Fine for me.

**Comment by Ana06** [comment]
@hennevogel, @adrianschroeter, @mdeniz, @smithfarm, @DavidKang, @sknorr, @evanrolfe, @ChrisBr, @fcrozat, @marcus-h, @wengel, @shyukri, @bmwiedemann ^^

**Comment by smithfarm** [comment]
@Ana06 I already applied my "thumbs-up" to the original description. So 👍 from my side.

**Comment by fcrozat** [comment]
fine for me

**Comment by DavidKang** [comment]
@Ana06, fine for me 😸

**Comment by mdeniz** [comment]
I agree to add it to everything 😄

**Comment by shyukri** [comment]
fine for me too

**Comment by evanrolfe** [comment]
fine for me

**Comment by marcus-h** [comment]
On 2017-12-28 10:52:42 +0000, Ana María Martínez Gómez wrote:
> I would suggest using a [Creative Commons Attribution 4.0](https://choosealicense.com/licenses/cc-by-4.0).
> 
Works for me.

> This can be applied only to new post, but it would be even better if we add it to old blog post as well. We could add the license to the old blog post, whose author/s are fine with it.
> 
Feel free to "re-license" my previous blog posts.

**Comment by ChrisBr** [comment]
LGTM

**Comment by hennevogel** [comment]
fine by me

**Comment by Ana06** [comment]
@adrianschroeter, @wengel, @bmwiedemann ^^

**Comment by wengel** [comment]
Good idea, fine with me.

**Comment by bmwiedemann** [comment]
sure. It is fine for me.
