### ISSUE TITLE
Track visits

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/obs-landing#190]
We should track visits in order to know how many people we reach with our landing page and especially with our blog. Once we have a setup to track this, we could then try different to increase our reach.

One possible solution to track visits is [jekyll-analytics](https://github.com/hendrikschneider/jekyll-analytics)

**Comment by hennevogel** [comment]
We already do with openSUSE's [piwik](https://github.com/openSUSE/obs-landing/blob/master/_layouts/default.html#L33)...

**Comment by dmarcoux** [comment]
How do we access the numbers?
