### ISSUE TITLE
30.000 users and 140.000 packages - comma missing?

### ISSUE THREAD

**Issue by V2dha** [openSUSE/obs-landing#306]
![Capture](https://user-images.githubusercontent.com/50369708/125513098-25cd773e-be63-4418-8a13-c543691a5156.PNG)

In the about section, is there supposed to be a comma indicating 30,000 users and 140,000 packages instead of a point?

**Comment by hennevogel** [comment]
Both are interchangeable, see [wikipedia](https://en.wikipedia.org/wiki/Decimal_separator).

![Screenshot from 2021-07-14 10-10-28](https://user-images.githubusercontent.com/514785/125587303-4cc302bc-ef9c-48da-afd1-21fcb666d379.png)

So the answer is: it's complicated 😃
